package it.saimao.tmkkeyboard.emojikeyboard.constants;

import it.saimao.tmkkeyboard.R;
import it.saimao.tmkkeyboard.utils.Utility;

public final class Emojione_EmojiIcons extends EmojiIcons {
    public Emojione_EmojiIcons() {
        transIconIds = Utility.initArrayList(
                R.drawable.emojione_emoji_1f3e0, R.drawable.emojione_emoji_1f3e1, R.drawable.emojione_emoji_1f3e2, R.drawable.emojione_emoji_1f3e3, R.drawable.emojione_emoji_1f3e4,
                R.drawable.emojione_emoji_1f3e5, R.drawable.emojione_emoji_1f3e6, R.drawable.emojione_emoji_1f3e7, R.drawable.emojione_emoji_1f3e8, R.drawable.emojione_emoji_1f3e9,
                R.drawable.emojione_emoji_1f3ea, R.drawable.emojione_emoji_1f3eb, R.drawable.emojione_emoji_26ea, R.drawable.emojione_emoji_26f2, R.drawable.emojione_emoji_1f3ec,
                R.drawable.emojione_emoji_1f3ef, R.drawable.emojione_emoji_1f3f0, R.drawable.emojione_emoji_1f3ed, R.drawable.emojione_emoji_1f5fb, R.drawable.emojione_emoji_1f5fc,
                R.drawable.emojione_emoji_1f488, R.drawable.emojione_emoji_1f527, R.drawable.emojione_emoji_1f528, R.drawable.emojione_emoji_1f529, R.drawable.emojione_emoji_1f6bf,
                R.drawable.emojione_emoji_1f6c1, R.drawable.emojione_emoji_1f6c0, R.drawable.emojione_emoji_1f6bd, R.drawable.emojione_emoji_1f6be, R.drawable.emojione_emoji_1f3bd,
                R.drawable.emojione_emoji_1f3a3, R.drawable.emojione_emoji_1f3b1, R.drawable.emojione_emoji_1f3b3, R.drawable.emojione_emoji_26be, R.drawable.emojione_emoji_26f3,
                R.drawable.emojione_emoji_1f3be, R.drawable.emojione_emoji_26bd, R.drawable.emojione_emoji_1f3bf, R.drawable.emojione_emoji_1f3c0, R.drawable.emojione_emoji_1f3c1,
                R.drawable.emojione_emoji_1f3c2, R.drawable.emojione_emoji_1f3c3, R.drawable.emojione_emoji_1f3c4, R.drawable.emojione_emoji_1f3c6, R.drawable.emojione_emoji_1f3c7,
                R.drawable.emojione_emoji_1f40e, R.drawable.emojione_emoji_1f3c8, R.drawable.emojione_emoji_1f3c9, R.drawable.emojione_emoji_1f3ca, R.drawable.emojione_emoji_1f682,
                R.drawable.emojione_emoji_1f683, R.drawable.emojione_emoji_1f684, R.drawable.emojione_emoji_1f685, R.drawable.emojione_emoji_1f686, R.drawable.emojione_emoji_1f687,
                R.drawable.emojione_emoji_24c2, R.drawable.emojione_emoji_1f688, R.drawable.emojione_emoji_1f68a, R.drawable.emojione_emoji_1f68b, R.drawable.emojione_emoji_1f68c,
                R.drawable.emojione_emoji_1f68d, R.drawable.emojione_emoji_1f68e, R.drawable.emojione_emoji_1f68f, R.drawable.emojione_emoji_1f690, R.drawable.emojione_emoji_1f691,
                R.drawable.emojione_emoji_1f692, R.drawable.emojione_emoji_1f693, R.drawable.emojione_emoji_1f694, R.drawable.emojione_emoji_1f695, R.drawable.emojione_emoji_1f696,
                R.drawable.emojione_emoji_1f697, R.drawable.emojione_emoji_1f698, R.drawable.emojione_emoji_1f699, R.drawable.emojione_emoji_1f69a, R.drawable.emojione_emoji_1f69b,
                R.drawable.emojione_emoji_1f69c, R.drawable.emojione_emoji_1f69d, R.drawable.emojione_emoji_1f69e, R.drawable.emojione_emoji_1f69f, R.drawable.emojione_emoji_1f6a0,
                R.drawable.emojione_emoji_1f6a1, R.drawable.emojione_emoji_1f6a2, R.drawable.emojione_emoji_1f6a3, R.drawable.emojione_emoji_1f681, R.drawable.emojione_emoji_2708,
                R.drawable.emojione_emoji_1f6c2, R.drawable.emojione_emoji_1f6c3, R.drawable.emojione_emoji_1f6c4, R.drawable.emojione_emoji_1f6c5, R.drawable.emojione_emoji_26f5,
                R.drawable.emojione_emoji_1f6b2, R.drawable.emojione_emoji_1f6b3, R.drawable.emojione_emoji_1f6b4, R.drawable.emojione_emoji_1f6b5, R.drawable.emojione_emoji_1f6b7,
                R.drawable.emojione_emoji_1f6b8, R.drawable.emojione_emoji_1f689, R.drawable.emojione_emoji_1f680, R.drawable.emojione_emoji_1f6a4, R.drawable.emojione_emoji_1f6b6,
                R.drawable.emojione_emoji_26fd, R.drawable.emojione_emoji_1f17f, R.drawable.emojione_emoji_1f6a5, R.drawable.emojione_emoji_1f6a6, R.drawable.emojione_emoji_1f6a7,
                R.drawable.emojione_emoji_1f6a8, R.drawable.emojione_emoji_2668, R.drawable.emojione_emoji_1f48c, R.drawable.emojione_emoji_1f48d, R.drawable.emojione_emoji_1f48e,
                R.drawable.emojione_emoji_1f490, R.drawable.emojione_emoji_1f492, R.drawable.emojione_emoji_fe4e5, R.drawable.emojione_emoji_fe4e6, R.drawable.emojione_emoji_fe4e7,
                R.drawable.emojione_emoji_fe4e8, R.drawable.emojione_emoji_fe4e9, R.drawable.emojione_emoji_fe4ea, R.drawable.emojione_emoji_fe4eb, R.drawable.emojione_emoji_fe4ec,
                R.drawable.emojione_emoji_fe4ed, R.drawable.emojione_emoji_fe4ee
        );

        thingsIconIds = Utility.initArrayList(
                //things
                R.drawable.emojione_emoji_1f530, R.drawable.emojione_emoji_1f484, R.drawable.emojione_emoji_1f45e, R.drawable.emojione_emoji_1f45f, R.drawable.emojione_emoji_1f451,
                R.drawable.emojione_emoji_1f452, R.drawable.emojione_emoji_1f3a9, R.drawable.emojione_emoji_1f393, R.drawable.emojione_emoji_1f453, R.drawable.emojione_emoji_231a,
                R.drawable.emojione_emoji_1f454, R.drawable.emojione_emoji_1f455, R.drawable.emojione_emoji_1f456, R.drawable.emojione_emoji_1f457, R.drawable.emojione_emoji_1f458,
                R.drawable.emojione_emoji_1f459, R.drawable.emojione_emoji_1f460, R.drawable.emojione_emoji_1f461, R.drawable.emojione_emoji_1f462, R.drawable.emojione_emoji_1f45a,
                R.drawable.emojione_emoji_1f45c, R.drawable.emojione_emoji_1f4bc, R.drawable.emojione_emoji_1f392, R.drawable.emojione_emoji_1f45d, R.drawable.emojione_emoji_1f45b,
                R.drawable.emojione_emoji_1f4b0, R.drawable.emojione_emoji_1f4b3, R.drawable.emojione_emoji_1f4b2, R.drawable.emojione_emoji_1f4b5, R.drawable.emojione_emoji_1f4b4,
                R.drawable.emojione_emoji_1f4b6, R.drawable.emojione_emoji_1f4b7, R.drawable.emojione_emoji_1f4b1, R.drawable.emojione_emoji_1f4b8, R.drawable.emojione_emoji_1f4b9,
                R.drawable.emojione_emoji_1f52b, R.drawable.emojione_emoji_1f52a, R.drawable.emojione_emoji_1f4a3, R.drawable.emojione_emoji_1f489, R.drawable.emojione_emoji_1f48a,
                R.drawable.emojione_emoji_1f6ac, R.drawable.emojione_emoji_1f514, R.drawable.emojione_emoji_1f515, R.drawable.emojione_emoji_1f6aa, R.drawable.emojione_emoji_1f52c,
                R.drawable.emojione_emoji_1f52d, R.drawable.emojione_emoji_1f52e, R.drawable.emojione_emoji_1f526, R.drawable.emojione_emoji_1f50b, R.drawable.emojione_emoji_1f50c,
                R.drawable.emojione_emoji_1f4dc, R.drawable.emojione_emoji_1f4d7, R.drawable.emojione_emoji_1f4d8, R.drawable.emojione_emoji_1f4d9, R.drawable.emojione_emoji_1f4da,
                R.drawable.emojione_emoji_1f4d4, R.drawable.emojione_emoji_1f4d2, R.drawable.emojione_emoji_1f4d1, R.drawable.emojione_emoji_1f4d3, R.drawable.emojione_emoji_1f4d5,
                R.drawable.emojione_emoji_1f4d6, R.drawable.emojione_emoji_1f4f0, R.drawable.emojione_emoji_1f4db, R.drawable.emojione_emoji_1f383, R.drawable.emojione_emoji_1f384,
                R.drawable.emojione_emoji_1f380, R.drawable.emojione_emoji_1f381, R.drawable.emojione_emoji_1f382, R.drawable.emojione_emoji_1f388, R.drawable.emojione_emoji_1f386,
                R.drawable.emojione_emoji_1f387, R.drawable.emojione_emoji_1f389, R.drawable.emojione_emoji_1f38a, R.drawable.emojione_emoji_1f38d, R.drawable.emojione_emoji_1f38f,
                R.drawable.emojione_emoji_1f38c, R.drawable.emojione_emoji_1f390, R.drawable.emojione_emoji_1f38b, R.drawable.emojione_emoji_1f38e, R.drawable.emojione_emoji_1f4f1,
                R.drawable.emojione_emoji_1f4f2, R.drawable.emojione_emoji_1f4df, R.drawable.emojione_emoji_260e, R.drawable.emojione_emoji_1f4de, R.drawable.emojione_emoji_1f4e0,
                R.drawable.emojione_emoji_1f4e6, R.drawable.emojione_emoji_2709, R.drawable.emojione_emoji_1f4e8, R.drawable.emojione_emoji_1f4e9, R.drawable.emojione_emoji_1f4ea,
                R.drawable.emojione_emoji_1f4eb, R.drawable.emojione_emoji_1f4ed, R.drawable.emojione_emoji_1f4ec, R.drawable.emojione_emoji_1f4ee, R.drawable.emojione_emoji_1f4e4,
                R.drawable.emojione_emoji_1f4e5, R.drawable.emojione_emoji_1f4ef, R.drawable.emojione_emoji_1f4e3, R.drawable.emojione_emoji_1f4e2, R.drawable.emojione_emoji_1f4e1,
                R.drawable.emojione_emoji_1f4ac, R.drawable.emojione_emoji_1f4ad, R.drawable.emojione_emoji_2712, R.drawable.emojione_emoji_270f, R.drawable.emojione_emoji_1f4dd,
                R.drawable.emojione_emoji_1f4cf, R.drawable.emojione_emoji_1f4d0, R.drawable.emojione_emoji_1f4cd, R.drawable.emojione_emoji_1f4cc, R.drawable.emojione_emoji_1f4ce,
                R.drawable.emojione_emoji_2702, R.drawable.emojione_emoji_1f4ba, R.drawable.emojione_emoji_1f4bb, R.drawable.emojione_emoji_1f4bd, R.drawable.emojione_emoji_1f4be,
                R.drawable.emojione_emoji_1f4bf, R.drawable.emojione_emoji_1f4c6, R.drawable.emojione_emoji_1f4c5, R.drawable.emojione_emoji_1f4c7, R.drawable.emojione_emoji_1f4cb,
                R.drawable.emojione_emoji_1f4c1, R.drawable.emojione_emoji_1f4c2, R.drawable.emojione_emoji_1f4c3, R.drawable.emojione_emoji_1f4c4, R.drawable.emojione_emoji_1f4ca,
                R.drawable.emojione_emoji_1f4c8, R.drawable.emojione_emoji_1f4c9, R.drawable.emojione_emoji_26fa, R.drawable.emojione_emoji_1f3a1, R.drawable.emojione_emoji_1f3a2,
                R.drawable.emojione_emoji_1f3a0, R.drawable.emojione_emoji_1f3aa, R.drawable.emojione_emoji_1f3a8, R.drawable.emojione_emoji_1f3ac, R.drawable.emojione_emoji_1f3a5,
                R.drawable.emojione_emoji_1f4f7, R.drawable.emojione_emoji_1f4f9, R.drawable.emojione_emoji_1f3a6, R.drawable.emojione_emoji_1f3ad, R.drawable.emojione_emoji_1f3ab,
                R.drawable.emojione_emoji_1f3ae, R.drawable.emojione_emoji_1f3b2, R.drawable.emojione_emoji_1f3b0, R.drawable.emojione_emoji_1f0cf, R.drawable.emojione_emoji_1f3b4,
                R.drawable.emojione_emoji_1f004, R.drawable.emojione_emoji_1f3af, R.drawable.emojione_emoji_1f4fa, R.drawable.emojione_emoji_1f4fb, R.drawable.emojione_emoji_1f4c0,
                R.drawable.emojione_emoji_1f4fc, R.drawable.emojione_emoji_1f3a7, R.drawable.emojione_emoji_1f3a4, R.drawable.emojione_emoji_1f3b5, R.drawable.emojione_emoji_1f3b6,
                R.drawable.emojione_emoji_1f3bc, R.drawable.emojione_emoji_1f3bb, R.drawable.emojione_emoji_1f3b9, R.drawable.emojione_emoji_1f3b7, R.drawable.emojione_emoji_1f3ba,
                R.drawable.emojione_emoji_1f3b8, R.drawable.emojione_emoji_303d
        );

        peopleIconIds = Utility.initArrayList(
                // people
                R.drawable.emojione_emoji_263a, R.drawable.emojione_emoji_1f60a, R.drawable.emojione_emoji_1f600, R.drawable.emojione_emoji_1f601, R.drawable.emojione_emoji_1f602,
                R.drawable.emojione_emoji_1f603, R.drawable.emojione_emoji_1f604, R.drawable.emojione_emoji_1f605, R.drawable.emojione_emoji_1f606, R.drawable.emojione_emoji_1f607,
                R.drawable.emojione_emoji_1f608, R.drawable.emojione_emoji_1f609, R.drawable.emojione_emoji_1f62f, R.drawable.emojione_emoji_1f610, R.drawable.emojione_emoji_1f611,
                R.drawable.emojione_emoji_1f615, R.drawable.emojione_emoji_1f620, R.drawable.emojione_emoji_1f62c, R.drawable.emojione_emoji_1f621, R.drawable.emojione_emoji_1f622,
                R.drawable.emojione_emoji_1f634, R.drawable.emojione_emoji_1f62e, R.drawable.emojione_emoji_1f623, R.drawable.emojione_emoji_1f624, R.drawable.emojione_emoji_1f625,
                R.drawable.emojione_emoji_1f626, R.drawable.emojione_emoji_1f627, R.drawable.emojione_emoji_1f628, R.drawable.emojione_emoji_1f629, R.drawable.emojione_emoji_1f630,
                R.drawable.emojione_emoji_1f61f, R.drawable.emojione_emoji_1f631, R.drawable.emojione_emoji_1f632, R.drawable.emojione_emoji_1f633, R.drawable.emojione_emoji_1f635,
                R.drawable.emojione_emoji_1f636, R.drawable.emojione_emoji_1f637, R.drawable.emojione_emoji_1f61e, R.drawable.emojione_emoji_1f612, R.drawable.emojione_emoji_1f60d,
                R.drawable.emojione_emoji_1f61b, R.drawable.emojione_emoji_1f61c, R.drawable.emojione_emoji_1f61d, R.drawable.emojione_emoji_1f60b, R.drawable.emojione_emoji_1f617,
                R.drawable.emojione_emoji_1f619, R.drawable.emojione_emoji_1f618, R.drawable.emojione_emoji_1f61a, R.drawable.emojione_emoji_1f60e, R.drawable.emojione_emoji_1f62d,
                R.drawable.emojione_emoji_1f60c, R.drawable.emojione_emoji_1f616, R.drawable.emojione_emoji_1f614, R.drawable.emojione_emoji_1f62a, R.drawable.emojione_emoji_1f60f,
                R.drawable.emojione_emoji_1f613, R.drawable.emojione_emoji_1f62b, R.drawable.emojione_emoji_1f64b, R.drawable.emojione_emoji_1f64c, R.drawable.emojione_emoji_1f64d,
                R.drawable.emojione_emoji_1f645, R.drawable.emojione_emoji_1f646, R.drawable.emojione_emoji_1f647, R.drawable.emojione_emoji_1f64e, R.drawable.emojione_emoji_1f64f,
                R.drawable.emojione_emoji_1f63a, R.drawable.emojione_emoji_1f63c, R.drawable.emojione_emoji_1f638, R.drawable.emojione_emoji_1f639, R.drawable.emojione_emoji_1f63b,
                R.drawable.emojione_emoji_1f63d, R.drawable.emojione_emoji_1f63f, R.drawable.emojione_emoji_1f63e, R.drawable.emojione_emoji_1f640, R.drawable.emojione_emoji_1f648,
                R.drawable.emojione_emoji_1f649, R.drawable.emojione_emoji_1f64a, R.drawable.emojione_emoji_1f4a9, R.drawable.emojione_emoji_1f476, R.drawable.emojione_emoji_1f466,
                R.drawable.emojione_emoji_1f467, R.drawable.emojione_emoji_1f468, R.drawable.emojione_emoji_1f469, R.drawable.emojione_emoji_1f474, R.drawable.emojione_emoji_1f475,
                R.drawable.emojione_emoji_1f48f, R.drawable.emojione_emoji_1f491, R.drawable.emojione_emoji_1f46a, R.drawable.emojione_emoji_1f46b, R.drawable.emojione_emoji_1f46c,
                R.drawable.emojione_emoji_1f46d, R.drawable.emojione_emoji_1f464, R.drawable.emojione_emoji_1f465, R.drawable.emojione_emoji_1f46e, R.drawable.emojione_emoji_1f477,
                R.drawable.emojione_emoji_1f481, R.drawable.emojione_emoji_1f482, R.drawable.emojione_emoji_1f46f, R.drawable.emojione_emoji_1f470, R.drawable.emojione_emoji_1f478,
                R.drawable.emojione_emoji_1f385, R.drawable.emojione_emoji_1f47c, R.drawable.emojione_emoji_1f471, R.drawable.emojione_emoji_1f472, R.drawable.emojione_emoji_1f473,
                R.drawable.emojione_emoji_1f483, R.drawable.emojione_emoji_1f486, R.drawable.emojione_emoji_1f487, R.drawable.emojione_emoji_1f485, R.drawable.emojione_emoji_1f47b,
                R.drawable.emojione_emoji_1f479, R.drawable.emojione_emoji_1f47a, R.drawable.emojione_emoji_1f47d, R.drawable.emojione_emoji_1f47e, R.drawable.emojione_emoji_1f47f,
                R.drawable.emojione_emoji_1f480, R.drawable.emojione_emoji_1f4aa, R.drawable.emojione_emoji_1f440, R.drawable.emojione_emoji_1f442, R.drawable.emojione_emoji_1f443,
                R.drawable.emojione_emoji_1f463, R.drawable.emojione_emoji_1f444, R.drawable.emojione_emoji_1f445, R.drawable.emojione_emoji_1f48b, R.drawable.emojione_emoji_2764,
                R.drawable.emojione_emoji_1f499, R.drawable.emojione_emoji_1f49a, R.drawable.emojione_emoji_1f49b, R.drawable.emojione_emoji_1f49c, R.drawable.emojione_emoji_1f493,
                R.drawable.emojione_emoji_1f494, R.drawable.emojione_emoji_1f495, R.drawable.emojione_emoji_1f496, R.drawable.emojione_emoji_1f497, R.drawable.emojione_emoji_1f498,
                R.drawable.emojione_emoji_1f49d, R.drawable.emojione_emoji_1f49e, R.drawable.emojione_emoji_1f49f, R.drawable.emojione_emoji_1f44d, R.drawable.emojione_emoji_1f44e,
                R.drawable.emojione_emoji_1f44c, R.drawable.emojione_emoji_270a, R.drawable.emojione_emoji_270c, R.drawable.emojione_emoji_270b, R.drawable.emojione_emoji_1f44a,
                R.drawable.emojione_emoji_261d, R.drawable.emojione_emoji_1f446, R.drawable.emojione_emoji_1f447, R.drawable.emojione_emoji_1f448, R.drawable.emojione_emoji_1f449,
                R.drawable.emojione_emoji_1f44b, R.drawable.emojione_emoji_1f44f, R.drawable.emojione_emoji_1f450
        );
        otherIconIds = Utility.initArrayList(
                // other
                R.drawable.emojione_emoji_1f51d, R.drawable.emojione_emoji_1f519, R.drawable.emojione_emoji_1f51b, R.drawable.emojione_emoji_1f51c, R.drawable.emojione_emoji_1f51a,
                R.drawable.emojione_emoji_23f3, R.drawable.emojione_emoji_231b, R.drawable.emojione_emoji_23f0, R.drawable.emojione_emoji_2648, R.drawable.emojione_emoji_2649,
                R.drawable.emojione_emoji_264a, R.drawable.emojione_emoji_264b, R.drawable.emojione_emoji_264c, R.drawable.emojione_emoji_264d, R.drawable.emojione_emoji_264e,
                R.drawable.emojione_emoji_264f, R.drawable.emojione_emoji_2650, R.drawable.emojione_emoji_2651, R.drawable.emojione_emoji_2652, R.drawable.emojione_emoji_2653,
                R.drawable.emojione_emoji_26ce, R.drawable.emojione_emoji_1f531, R.drawable.emojione_emoji_1f52f, R.drawable.emojione_emoji_1f6bb, R.drawable.emojione_emoji_1f6ae,
                R.drawable.emojione_emoji_1f6af, R.drawable.emojione_emoji_1f6b0, R.drawable.emojione_emoji_1f6b1, R.drawable.emojione_emoji_1f170, R.drawable.emojione_emoji_1f171,
                R.drawable.emojione_emoji_1f18e, R.drawable.emojione_emoji_1f17e, R.drawable.emojione_emoji_1f4ae, R.drawable.emojione_emoji_1f4af, R.drawable.emojione_emoji_1f520,
                R.drawable.emojione_emoji_1f521, R.drawable.emojione_emoji_1f522, R.drawable.emojione_emoji_1f523, R.drawable.emojione_emoji_1f524, R.drawable.emojione_emoji_27bf,
                R.drawable.emojione_emoji_1f4f6, R.drawable.emojione_emoji_1f4f3, R.drawable.emojione_emoji_1f4f4, R.drawable.emojione_emoji_1f4f5, R.drawable.emojione_emoji_1f6b9,
                R.drawable.emojione_emoji_1f6ba, R.drawable.emojione_emoji_1f6bc, R.drawable.emojione_emoji_267f, R.drawable.emojione_emoji_267b, R.drawable.emojione_emoji_1f6ad,
                R.drawable.emojione_emoji_1f6a9, R.drawable.emojione_emoji_26a0, R.drawable.emojione_emoji_1f201, R.drawable.emojione_emoji_1f51e, R.drawable.emojione_emoji_26d4,
                R.drawable.emojione_emoji_1f192, R.drawable.emojione_emoji_1f197, R.drawable.emojione_emoji_1f195, R.drawable.emojione_emoji_1f198, R.drawable.emojione_emoji_1f199,
                R.drawable.emojione_emoji_1f193, R.drawable.emojione_emoji_1f196, R.drawable.emojione_emoji_1f19a, R.drawable.emojione_emoji_1f232, R.drawable.emojione_emoji_1f233,
                R.drawable.emojione_emoji_1f234, R.drawable.emojione_emoji_1f235, R.drawable.emojione_emoji_1f236, R.drawable.emojione_emoji_1f237, R.drawable.emojione_emoji_1f238,
                R.drawable.emojione_emoji_1f239, R.drawable.emojione_emoji_1f202, R.drawable.emojione_emoji_1f23a, R.drawable.emojione_emoji_1f250, R.drawable.emojione_emoji_1f251,
                R.drawable.emojione_emoji_3299, R.drawable.emojione_emoji_00ae, R.drawable.emojione_emoji_00a9, R.drawable.emojione_emoji_2122, R.drawable.emojione_emoji_1f21a,
                R.drawable.emojione_emoji_1f22f, R.drawable.emojione_emoji_3297, R.drawable.emojione_emoji_2b55, R.drawable.emojione_emoji_274c, R.drawable.emojione_emoji_274e,
                R.drawable.emojione_emoji_2139, R.drawable.emojione_emoji_1f6ab, R.drawable.emojione_emoji_2705, R.drawable.emojione_emoji_2714, R.drawable.emojione_emoji_1f517,
                R.drawable.emojione_emoji_2734, R.drawable.emojione_emoji_2733, R.drawable.emojione_emoji_2795, R.drawable.emojione_emoji_2796, R.drawable.emojione_emoji_2716,
                R.drawable.emojione_emoji_2797, R.drawable.emojione_emoji_1f4a0, R.drawable.emojione_emoji_1f4a1, R.drawable.emojione_emoji_1f4a4, R.drawable.emojione_emoji_1f4a2,
                R.drawable.emojione_emoji_1f525, R.drawable.emojione_emoji_1f4a5, R.drawable.emojione_emoji_1f4a6, R.drawable.emojione_emoji_1f4a8, R.drawable.emojione_emoji_1f4ab,
                R.drawable.emojione_emoji_1f55b, R.drawable.emojione_emoji_1f567, R.drawable.emojione_emoji_1f550, R.drawable.emojione_emoji_1f55c, R.drawable.emojione_emoji_1f551,
                R.drawable.emojione_emoji_1f55d, R.drawable.emojione_emoji_1f552, R.drawable.emojione_emoji_1f55e, R.drawable.emojione_emoji_1f553, R.drawable.emojione_emoji_1f55f,
                R.drawable.emojione_emoji_1f554, R.drawable.emojione_emoji_1f560, R.drawable.emojione_emoji_1f555, R.drawable.emojione_emoji_1f561, R.drawable.emojione_emoji_1f556,
                R.drawable.emojione_emoji_1f562, R.drawable.emojione_emoji_1f557, R.drawable.emojione_emoji_1f563, R.drawable.emojione_emoji_1f558, R.drawable.emojione_emoji_1f564,
                R.drawable.emojione_emoji_1f559, R.drawable.emojione_emoji_1f565, R.drawable.emojione_emoji_1f55a, R.drawable.emojione_emoji_1f566, R.drawable.emojione_emoji_2195,
                R.drawable.emojione_emoji_2b06, R.drawable.emojione_emoji_2197, R.drawable.emojione_emoji_27a1, R.drawable.emojione_emoji_2198, R.drawable.emojione_emoji_2b07,
                R.drawable.emojione_emoji_2199, R.drawable.emojione_emoji_2b05, R.drawable.emojione_emoji_2196, R.drawable.emojione_emoji_2194, R.drawable.emojione_emoji_2934,
                R.drawable.emojione_emoji_2935, R.drawable.emojione_emoji_23ea, R.drawable.emojione_emoji_23e9, R.drawable.emojione_emoji_23eb, R.drawable.emojione_emoji_23ec,
                R.drawable.emojione_emoji_25c0, R.drawable.emojione_emoji_25b6, R.drawable.emojione_emoji_1f53d, R.drawable.emojione_emoji_1f53c, R.drawable.emojione_emoji_2747,
                R.drawable.emojione_emoji_2728, R.drawable.emojione_emoji_1f534, R.drawable.emojione_emoji_1f535, R.drawable.emojione_emoji_26aa, R.drawable.emojione_emoji_26ab,
                R.drawable.emojione_emoji_1f533, R.drawable.emojione_emoji_1f532, R.drawable.emojione_emoji_2b50, R.drawable.emojione_emoji_1f31f, R.drawable.emojione_emoji_1f320,
                R.drawable.emojione_emoji_25ab, R.drawable.emojione_emoji_25aa, R.drawable.emojione_emoji_25fd, R.drawable.emojione_emoji_25fe, R.drawable.emojione_emoji_25fc,
                R.drawable.emojione_emoji_25fb, R.drawable.emojione_emoji_2b1b, R.drawable.emojione_emoji_2b1c, R.drawable.emojione_emoji_1f539, R.drawable.emojione_emoji_1f538,
                R.drawable.emojione_emoji_1f537, R.drawable.emojione_emoji_1f536, R.drawable.emojione_emoji_1f53a, R.drawable.emojione_emoji_1f53b, R.drawable.emojione_emoji_1f51f,
                R.drawable.emojione_emoji_20e3, R.drawable.emojione_emoji_2754, R.drawable.emojione_emoji_2753, R.drawable.emojione_emoji_2755, R.drawable.emojione_emoji_2757,
                R.drawable.emojione_emoji_203c, R.drawable.emojione_emoji_2049, R.drawable.emojione_emoji_3030, R.drawable.emojione_emoji_27b0, R.drawable.emojione_emoji_2660,
                R.drawable.emojione_emoji_2665, R.drawable.emojione_emoji_2663, R.drawable.emojione_emoji_2666, R.drawable.emojione_emoji_1f194, R.drawable.emojione_emoji_1f511,
                R.drawable.emojione_emoji_21a9, R.drawable.emojione_emoji_1f191, R.drawable.emojione_emoji_1f50d, R.drawable.emojione_emoji_1f512, R.drawable.emojione_emoji_1f513,
                R.drawable.emojione_emoji_21aa, R.drawable.emojione_emoji_1f510, R.drawable.emojione_emoji_2611, R.drawable.emojione_emoji_1f518, R.drawable.emojione_emoji_1f50e,
                R.drawable.emojione_emoji_1f516, R.drawable.emojione_emoji_1f50f, R.drawable.emojione_emoji_1f503, R.drawable.emojione_emoji_1f500, R.drawable.emojione_emoji_1f501,
                R.drawable.emojione_emoji_1f502, R.drawable.emojione_emoji_1f504, R.drawable.emojione_emoji_1f4e7, R.drawable.emojione_emoji_1f505, R.drawable.emojione_emoji_1f506,
                R.drawable.emojione_emoji_1f507, R.drawable.emojione_emoji_1f508, R.drawable.emojione_emoji_1f509, R.drawable.emojione_emoji_1f50a, R.drawable.emojione_emoji_1f1e6,
                R.drawable.emojione_emoji_1f1e7, R.drawable.emojione_emoji_1f1e8, R.drawable.emojione_emoji_1f1e9, R.drawable.emojione_emoji_1f1ea, R.drawable.emojione_emoji_1f1eb,
                R.drawable.emojione_emoji_1f1ec, R.drawable.emojione_emoji_1f1ed, R.drawable.emojione_emoji_1f1ee, R.drawable.emojione_emoji_1f1ef, R.drawable.emojione_emoji_1f1f0,
                R.drawable.emojione_emoji_1f1f1, R.drawable.emojione_emoji_1f1f2, R.drawable.emojione_emoji_1f1f3, R.drawable.emojione_emoji_1f1f4, R.drawable.emojione_emoji_1f1f5,
                R.drawable.emojione_emoji_1f1f6, R.drawable.emojione_emoji_1f1f7, R.drawable.emojione_emoji_1f1f8, R.drawable.emojione_emoji_1f1f9, R.drawable.emojione_emoji_1f1fa,
                R.drawable.emojione_emoji_1f1fb, R.drawable.emojione_emoji_1f1fc, R.drawable.emojione_emoji_1f1fd, R.drawable.emojione_emoji_1f1fe, R.drawable.emojione_emoji_1f1ff
        );

        natureIconIds = Utility.initArrayList(
                // nature
                R.drawable.emojione_emoji_1f415, R.drawable.emojione_emoji_1f436, R.drawable.emojione_emoji_1f429, R.drawable.emojione_emoji_1f408, R.drawable.emojione_emoji_1f431,
                R.drawable.emojione_emoji_1f400, R.drawable.emojione_emoji_1f401, R.drawable.emojione_emoji_1f42d, R.drawable.emojione_emoji_1f439, R.drawable.emojione_emoji_1f422,
                R.drawable.emojione_emoji_1f407, R.drawable.emojione_emoji_1f430, R.drawable.emojione_emoji_1f413, R.drawable.emojione_emoji_1f414, R.drawable.emojione_emoji_1f423,
                R.drawable.emojione_emoji_1f424, R.drawable.emojione_emoji_1f425, R.drawable.emojione_emoji_1f426, R.drawable.emojione_emoji_1f40f, R.drawable.emojione_emoji_1f411,
                R.drawable.emojione_emoji_1f410, R.drawable.emojione_emoji_1f43a, R.drawable.emojione_emoji_1f403, R.drawable.emojione_emoji_1f402, R.drawable.emojione_emoji_1f404,
                R.drawable.emojione_emoji_1f42e, R.drawable.emojione_emoji_1f434, R.drawable.emojione_emoji_1f417, R.drawable.emojione_emoji_1f416, R.drawable.emojione_emoji_1f437,
                R.drawable.emojione_emoji_1f43d, R.drawable.emojione_emoji_1f438, R.drawable.emojione_emoji_1f40d, R.drawable.emojione_emoji_1f43c, R.drawable.emojione_emoji_1f427,
                R.drawable.emojione_emoji_1f418, R.drawable.emojione_emoji_1f428, R.drawable.emojione_emoji_1f412, R.drawable.emojione_emoji_1f435, R.drawable.emojione_emoji_1f406,
                R.drawable.emojione_emoji_1f42f, R.drawable.emojione_emoji_1f43b, R.drawable.emojione_emoji_1f42a, R.drawable.emojione_emoji_1f42b, R.drawable.emojione_emoji_1f40a,
                R.drawable.emojione_emoji_1f433, R.drawable.emojione_emoji_1f40b, R.drawable.emojione_emoji_1f41f, R.drawable.emojione_emoji_1f420, R.drawable.emojione_emoji_1f421,
                R.drawable.emojione_emoji_1f419, R.drawable.emojione_emoji_1f41a, R.drawable.emojione_emoji_1f42c, R.drawable.emojione_emoji_1f40c, R.drawable.emojione_emoji_1f41b,
                R.drawable.emojione_emoji_1f41c, R.drawable.emojione_emoji_1f41d, R.drawable.emojione_emoji_1f41e, R.drawable.emojione_emoji_1f432, R.drawable.emojione_emoji_1f409,
                R.drawable.emojione_emoji_1f43e, R.drawable.emojione_emoji_1f378, R.drawable.emojione_emoji_1f37a, R.drawable.emojione_emoji_1f37b, R.drawable.emojione_emoji_1f377,
                R.drawable.emojione_emoji_1f379, R.drawable.emojione_emoji_1f376, R.drawable.emojione_emoji_2615, R.drawable.emojione_emoji_1f375, R.drawable.emojione_emoji_1f37c,
                R.drawable.emojione_emoji_1f374, R.drawable.emojione_emoji_1f368, R.drawable.emojione_emoji_1f367, R.drawable.emojione_emoji_1f366, R.drawable.emojione_emoji_1f369,
                R.drawable.emojione_emoji_1f370, R.drawable.emojione_emoji_1f36a, R.drawable.emojione_emoji_1f36b, R.drawable.emojione_emoji_1f36c, R.drawable.emojione_emoji_1f36d,
                R.drawable.emojione_emoji_1f36e, R.drawable.emojione_emoji_1f36f, R.drawable.emojione_emoji_1f373, R.drawable.emojione_emoji_1f354, R.drawable.emojione_emoji_1f35f,
                R.drawable.emojione_emoji_1f35d, R.drawable.emojione_emoji_1f355, R.drawable.emojione_emoji_1f356, R.drawable.emojione_emoji_1f357, R.drawable.emojione_emoji_1f364,
                R.drawable.emojione_emoji_1f363, R.drawable.emojione_emoji_1f371, R.drawable.emojione_emoji_1f35e, R.drawable.emojione_emoji_1f35c, R.drawable.emojione_emoji_1f359,
                R.drawable.emojione_emoji_1f35a, R.drawable.emojione_emoji_1f35b, R.drawable.emojione_emoji_1f372, R.drawable.emojione_emoji_1f365, R.drawable.emojione_emoji_1f362,
                R.drawable.emojione_emoji_1f361, R.drawable.emojione_emoji_1f358, R.drawable.emojione_emoji_1f360, R.drawable.emojione_emoji_1f34c, R.drawable.emojione_emoji_1f34e,
                R.drawable.emojione_emoji_1f34f, R.drawable.emojione_emoji_1f34a, R.drawable.emojione_emoji_1f34b, R.drawable.emojione_emoji_1f344, R.drawable.emojione_emoji_1f345,
                R.drawable.emojione_emoji_1f346, R.drawable.emojione_emoji_1f347, R.drawable.emojione_emoji_1f348, R.drawable.emojione_emoji_1f349, R.drawable.emojione_emoji_1f350,
                R.drawable.emojione_emoji_1f351, R.drawable.emojione_emoji_1f352, R.drawable.emojione_emoji_1f353, R.drawable.emojione_emoji_1f34d, R.drawable.emojione_emoji_1f330,
                R.drawable.emojione_emoji_1f331, R.drawable.emojione_emoji_1f332, R.drawable.emojione_emoji_1f333, R.drawable.emojione_emoji_1f334, R.drawable.emojione_emoji_1f335,
                R.drawable.emojione_emoji_1f337, R.drawable.emojione_emoji_1f338, R.drawable.emojione_emoji_1f339, R.drawable.emojione_emoji_1f340, R.drawable.emojione_emoji_1f341,
                R.drawable.emojione_emoji_1f342, R.drawable.emojione_emoji_1f343, R.drawable.emojione_emoji_1f33a, R.drawable.emojione_emoji_1f33b, R.drawable.emojione_emoji_1f33c,
                R.drawable.emojione_emoji_1f33d, R.drawable.emojione_emoji_1f33e, R.drawable.emojione_emoji_1f33f, R.drawable.emojione_emoji_2600, R.drawable.emojione_emoji_1f308,
                R.drawable.emojione_emoji_26c5, R.drawable.emojione_emoji_2601, R.drawable.emojione_emoji_1f301, R.drawable.emojione_emoji_1f302, R.drawable.emojione_emoji_2614,
                R.drawable.emojione_emoji_1f4a7, R.drawable.emojione_emoji_26a1, R.drawable.emojione_emoji_1f300, R.drawable.emojione_emoji_2744, R.drawable.emojione_emoji_26c4,
                R.drawable.emojione_emoji_1f319, R.drawable.emojione_emoji_1f31e, R.drawable.emojione_emoji_1f31d, R.drawable.emojione_emoji_1f31a, R.drawable.emojione_emoji_1f31b,
                R.drawable.emojione_emoji_1f31c, R.drawable.emojione_emoji_1f311, R.drawable.emojione_emoji_1f312, R.drawable.emojione_emoji_1f313, R.drawable.emojione_emoji_1f314,
                R.drawable.emojione_emoji_1f315, R.drawable.emojione_emoji_1f316, R.drawable.emojione_emoji_1f317, R.drawable.emojione_emoji_1f318, R.drawable.emojione_emoji_1f391,
                R.drawable.emojione_emoji_1f304, R.drawable.emojione_emoji_1f305, R.drawable.emojione_emoji_1f307, R.drawable.emojione_emoji_1f306, R.drawable.emojione_emoji_1f303,
                R.drawable.emojione_emoji_1f30c, R.drawable.emojione_emoji_1f309, R.drawable.emojione_emoji_1f30a, R.drawable.emojione_emoji_1f30b, R.drawable.emojione_emoji_1f30e,
                R.drawable.emojione_emoji_1f30f, R.drawable.emojione_emoji_1f30d, R.drawable.emojione_emoji_1f310
        );
    }
}